# Generated by Django 5.1.5 on 2025-02-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('warrenty_expration_Date', models.DateField()),
                ('opinion', models.TextField(max_length=250)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
