# Generated by Django 5.1.5 on 2025-02-10 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('P', 'Smart Phone'), ('L', 'Laptops'), ('M', 'Machines'), ('T', 'Tablet'), ('O', 'Others')], default=0, max_length=1)),
                ('description', models.TextField(max_length=250)),
                ('rate', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('warrenty_expration_Date', models.DateField()),
                ('opinion', models.TextField(max_length=250)),
                ('likes', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=250)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
