# Generated by Django 5.1.5 on 2025-02-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('P', 'Smart Phone'), ('L', 'Laptops'), ('M', 'Machines'), ('T', 'Tablet'), ('O', 'Others')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
