# Generated by Django 4.2.19 on 2025-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.TextField(choices=[('P', 'Smart Phone'), ('L', 'Laptops'), ('M', 'Machines'), ('T', 'Tablet'), ('O', 'Others')], default='P', max_length=1),
        ),
    ]
