# Generated by Django 5.1.5 on 2025-02-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews2',
        ),
    ]
