# Generated by Django 4.2.19 on 2025-02-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_device_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
