# Generated by Django 5.1.5 on 2025-02-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_reviews_options'),
        ('main_app', '0003_reviews2'),
    ]

    operations = [
    ]
