# Generated by Django 4.2.19 on 2025-02-19 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_alter_device_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.device'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('sender', 'receiver')},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='date_time',
        ),
    ]
